name: Publish Python Package to PyPI on Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Create and publish a release to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pdm install --prod

      - name: Build and Publish
        env:
          PDM_PUBLISH_USERNAME: __token__
          PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pdm publish
